# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'minitest'
gem 'rerun'
gem 'rubocop'
gem 'rubocop-minitest'
gem 'rubocop-performance'
